[workspace]
name = "instanseg-fiji"
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[dependencies]
python = "3.11.*"
openjdk = "11.*"
numpy = "*"
scipy = "*"
scikit-image = "*"
pandas = "*"
tifffile = "*"
napari = "*"
pyqt = "*"
jupyter = "*"
jupyterlab = "*"
ipykernel = "*"
roifile = "*"

[pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu118"]

[pypi-dependencies]
appose = "*"
bioio-nd2 = "*"
bioio-tifffile = "*"
bioio-bioformats = "*"
bioio = "*"
customtkinter = "*"
instanseg-torch = "*"
colorama = "*"
torch = { version = "*", index = "https://download.pytorch.org/whl/cu118" }
torchvision = { version = "*", index = "https://download.pytorch.org/whl/cu118" }
scikit-image = "*"